name: Convert DOCX and LaTeX Files

on:
  push:
    paths:
      - 'input/**.docx'
      - 'input/**.tex'
  workflow_dispatch:

jobs:
  convert-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Create directories
        run: mkdir -p input output
      
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx fpdf
      
      - name: Run converter script
        run: python converter.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/ README.md
          git commit -m 'Convert files and update README' || echo "No changes to commit"
          git push || echo "No changes to push"