name: Convert DOCX and LaTeX Files

on:
  push:
    paths:
      - '**.docx'
      - '**.tex'
      - 'input/**'
      - 'converter.py'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

  install-dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libreoffice \
            texlive-latex-base \
            texlive-fonts-recommended
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install docx2pdf

  convert:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run converter script
        run: python converter.py

  publish:
    needs: convert
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md output/
          git diff --staged --quiet || git commit -m "Convert files and update README"
      - name: Push changes
        run: git push