name: Convert DOCX and LaTeX Files

on:
  push:
    paths:
      - '**.docx'
      - '**.tex'
      - 'input/**'
      - 'converter.py'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.docx'
      - '**.tex'
      - 'input/**'
  workflow_dispatch:

jobs:
  convert-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Only fetch the latest commit
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libreoffice \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-latex-recommended
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docx2pdf
      
      - name: Run converter script
        run: python converter.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git diff --staged --quiet || git commit -m "Convert files and update README"
          git push