name: Convert DOCX and LaTeX Files

on:
  push:
    paths:
      - 'input/**.docx'
      - 'input/**.tex'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      
      - name: Create directories
        run: mkdir -p input output
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  install-dependencies:
    needs: setup
    runs-on: ubuntu-24
    steps:
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx fpdf

  convert:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run converter script
        run: python converter.py

  publish:
    needs: convert
    if: success()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add output/ README.md
          git commit -m 'Convert files and update README'
          git push